name: ğŸ”¨ Building env dbt models ğŸ‘¾

on: [push]

jobs:
  Test-Development-Initialization:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout Branch
        uses: actions/checkout@v3

      - name: ğŸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Install Python Requirements
        run: pip install -r requirements.txt
        
      - name: ğŸ› ï¸ Initialize Database and Run dbt
        run: sh github-actions-psql-init.sh

      - name: ğŸš€ Run dbt Commands
        run: |
          cd ./northwind
          dbt deps
          dbt snapshot --profiles-dir ..
          dbt run --profiles-dir ..
          dbt run --full-refresh --profiles-dir ..
          dbt test --profiles-dir ..