name: ğŸ”¨ Building env dbt models ğŸ‘¾

on:
  pull_request:
    branches: [main]

jobs:
  Test-Development-Initialization:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout Branch
        uses: actions/checkout@v3

      - name: ğŸ Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: ğŸ“¦ Install Python Requirements
        run: pip install -r requirements.txt
        
      - name: ğŸ› ï¸ Initialize Database and Run dbt
        run: sh github-actions-psql-init.sh
     
      - name: ğŸš€ Run dbt Commands
        env:
          NORTHWIND_DB_NAME: ${{ secrets.NORTHWIND_DB_NAME }}
          NORTHWIND_DB_USER: ${{ secrets.NORTHWIND_USERNAME }}
          NORTHWIND_DB_PASSWORD: ${{ secrets.NORTHWIND_PASSWORD }}
          NORTHWIND_DB_HOST: ${{ secrets.NORTHWIND_HOST }}
          NORTHWIND_DB_SCHEMA: ${{ secrets.NORTHWIND_DBT_SCHEMA }}
        run: |
          cd ./northwind
          dbt debug
          dbt deps
          dbt snapshot
          dbt run -f
          dbt run 
          dbt test
